name: Run Jest Tests

on:
  push:
    branches:
      - mobile-app

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Node.js with caching for subdirectory
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'
          cache: 'npm'
          cache-dependency-path: BarcodeScannerApp/BarcodeMLApp/package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          npx jest --clearCache
        working-directory: BarcodeScannerApp/BarcodeMLApp

      # Step 4: Run Jest tests
      - name: Run tests
        run: npm test
        working-directory: BarcodeScannerApp/BarcodeMLApp
